### ISSUE TITLE
Dutch locale not respected

### ISSUE THREAD

**Issue by voicecode-bv** [mitydigital/statamic-two-factor#19]
### Bug description

Although there is a Dutch translation folder (nl_NL) available, it's not respected. 

### Steps to reproduce

Rename the nl_NL folder to nl solves the issue

### Environment and versions

```yaml
Environment
Application Name: My App
Laravel Version: 11.29.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: my-app.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.33.1 PRO

Statamic Addons
mitydigital/statamic-two-factor: 2.2.2
```
