### ISSUE TITLE
Unable to use 2FA

### ISSUE THREAD

**Issue by dnwjn** [mitydigital/statamic-two-factor#23]
### Bug description

We're unable to use 2FA. The first issue is that it seems that after the validity expires (we use the default of `43200`), the users are not able to log in anymore, because the 2FA code doesn't work, nor does a recovery code.

Secondly, we're also unable to set up 2FA now. For our own user we removed all 2FA related data from the user in the database. Then, after logging in, we had to set up 2FA again. However, when scanning the QR and entering the code, we get an error:

![Image](https://github.com/user-attachments/assets/94f2d69a-cae6-4391-b2ad-6a533d879ca5)

Unfortunately, this is currently unusable, forcing us to disable the package.

Weirdly enough, this is only happening in our production environment, not local.

### Steps to reproduce

1. Reset all 2FA related user data from the user in the database, if any
2. Log in
3. Try to set up the 2FA

### Environment and versions

```yaml
Environment
Laravel Version: 10.48.25
PHP Version: 8.2.27
Environment: production

Statamic
Addons: 4
Sites: 3
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
mitydigital/statamic-two-factor: 2.3.0
statamic/eloquent-driver: 4.18.0
stoffelio/statamic-404-logger: 1.1.0
superinteractive/statamic-super-link: 1.0.1

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: redis

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```
