### ISSUE TITLE
Compatibility issue with Wordpress Users addon for Statamic

### ISSUE THREAD

**Issue by bellevue7k-user** [mitydigital/statamic-two-factor#29]
### Bug description

Hi,
we recently encountered what seems to be a compatibility issue when using two-factor authentication in combination with the [WordPress Users addon by Arthur Perton](https://statamic.com/addons/arthurperton/wordpress-users). When having both addons installed, setting up two-factor authentication fails. After scanning the QR code, entering the six-digit authentication code results in an error message saying that the entered code is invalid.

![Image](https://github.com/user-attachments/assets/a759945d-c434-4ed6-a5a1-c34445d326da)

After uninstalling the wordpress-users addon, setting up 2FA works as expected again.

This issue only seems to affect the initial setup of 2FA though, once 2FA is set up for a user, they can log in using their authentication code just fine even with wordpress-users installed.

Any ideas for a potential workaround/fix? Right now we are simply uninstalling the wordpress-users addon after importing all users, but this is suboptimal as it means users can't use their original wordpress password to log in and need to use the password reset option first.

### Steps to reproduce

1. Install the statamic-two-factor addon through composer and enable 2FA.
2. Install the wordpress-users addon through composer
3. Create a new user
4. Attempt to log in as the new user, prompt to setup 2FA appears
5. Scan QR code with authenticator app, enter the authentication code -> error message shows, saying that the entered code is invalid
6. Uninstall wordpress-users
7. Try setting up 2FA again, should work now

### Environment and versions

```yaml
Environment

Laravel Version: 11.40.0
PHP Version: 8.3.17
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: foo.test
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de_CH

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
arthurperton/wordpress-users: 1.2.0
aryehraber/statamic-logbook: 3.3.0
mitydigital/statamic-two-factor: 2.5.0
```
