### ISSUE TITLE
2FA error after Statamic update

### ISSUE THREAD

**Issue by itsserbin** [mitydigital/statamic-two-factor#32]
### Bug description

Hi, after updating Statamic to the latest version I get an error when trying to authorize with the 2fa plugin 
I also updated 2fa and the eloquent driver but the error is still here

MityDigital\StatamicTwoFactor\Actions\ChallengeTwoFactorAuthentication::__invoke(): Argument #1 ($user) must be of type Statamic\Auth\User, App\Models\User given, called in /Users/admin/PhpstormProjects/youscan-promosite-backend/vendor/mitydigital/statamic-two-factor/src/Http/Controllers/TwoFactorChallengeController.php on line 61

### Steps to reproduce

Update Statamic/2FA/EloquentDrive to latest version and enable 2FA

### Environment and versions

```yaml
~/PhpstormProjects/youscan-promosite-backend git:[master]
php please support:details

Environment
Application Name: Laravel
Laravel Version: 12.17.0
PHP Version: 8.3.21
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: pgsql
Logs: google
Mail: smtp
Queue: database
Session: database

Storage
public/storage: LINKED

Statamic
Addons: 4
Sites: 4 (English, Spanish, Ukrainian, Portuguese)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
mitydigital/statamic-two-factor: 2.6.0
statamic/eloquent-driver: 4.23.3
stillat/relationships: 2.2.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
